CREATE DATABASE IF NOT EXISTS teste_sofware
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
USE teste_sofware;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);